version: "3.7"

services:
  product:
    build:
      context: .
      dockerfile: Dockerfile.hotreload
    networks:
      - backend
    ports:
      - "5001:5000"
    expose:
      - 5000
    volumes:
      - .:/go/src/product

networks: 
  backend:
    driver: bridge
    external: true
  frontend:
    driver: bridge