version: "3.7"
services:
  auth-service:
    build: ./go-auth
    # command: air
    volumes:
      - ./go-auth:/src/
    networks:
      - backend
      - frontend
    ports:
      - 80:80
    expose:
      - 80
  api-todo:
    build:
      context: ./api-graphql
    networks:
      - backend
      - frontend
    ports:
      - 4000:4000
    expose:
      - 4000

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    networks:
      - backend
    expose:
      - 3000

  prom-server:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    networks:
      - backend
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
  # jaeger:
    # 

  # web:
  #   build:
  #     context: ./todo-site
  #   networks:
  #     - frontend
  #   ports:
  #     - 8080:80
  
networks: 
  backend:
    driver: bridge
    external: true
  frontend:
    driver: bridge
