version: "3.7"
services:
  auth-service:
    build:
      context: ./go-auth
    networks:
      - backend
      - frontend
    ports:
      - 80:80
  api-todo:
    build:
      context: ./api-graphql
    networks:
      - backend
      - frontend
    ports:
      - 4000:4000

  # jaeger:
    # 

  # web:
  #   build:
  #     context: ./todo-site
  #   networks:
  #     - frontend
  #   ports:
  #     - 8080:80
  
networks: 
  backend:
    driver: bridge
  frontend:
    driver: bridge
