apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl:
    manifests:
      - './k8s/*'
build: 
  local: 
    push: false
  artifacts:
    - image: to-do-list-microservices_auth-service
      context: go-auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'internal/**/*.go'
  