FROM golang:1.15-alpine

RUN apk add build-base
RUN apk --no-cache add make git gcc libtool musl-dev ca-certificates dumb-init 
# ENV CGO_ENABLED=0

WORKDIR /go/src/go-auth
COPY . .
RUN go mod download

RUN go build .

EXPOSE 80

CMD ["./go-auth"]