version: "3.7"

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
      # - '9093:9093'
    expose:
      - "9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT
      # - KAFKA_CFG_LISTENERS=EXTERNAL://localhost:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      # - KAFKA_CLIENT_USER=user
      # - KAFKA_CLIENT_PASSWORD=password
    depends_on:
      - zookeeper
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    networks:
      - backend
    expose:
      - 3000
    volumes:
      - ./grafana/config/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config/provisioning/dashboards:/etc/grafana/provisioning/dashboards

  prom-server:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    networks:
      - backend
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1.28
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - backend

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks: 
  backend:
    driver: bridge
    external: true
  frontend:
    driver: bridge
