version: "3.7"

services:
  booking:
    build:
      context: .
      dockerfile: Dockerfile.hotreload
    networks:
      - backend
    ports:
      - "4000:4000"
    expose:
      - 4000
    volumes:
      - .:/go/src/booking
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks: 
  backend:
    driver: bridge
    external: true
  frontend:
    driver: bridge