# a very minimal declarative config file
_format_version: "2.1"
plugins:
- name: prometheus
# - name: rate-limiting
#   config:
#     minute: 5
#     policy: local
# - name: grpc-gateway
#   config: 
#     proto: ../product/proto/product.proto
services:
  - name: metrics
    url: http://127.0.0.1:8001/metrics
    routes:
    - name: metrics
      paths:
        - /metrics
      strip_path: true
  - name: product-http
    host: product
    port: 5000
    protocol: http
    routes:
    - name: product
      paths:
        - /product
      strip_path: true
  - name: booking-http
    host: booking
    port: 4000
    protocol: http
    routes:
    - name: booking
      paths:
        - /booking
      strip_path: true
  # - name: payment-http
  #   url: http://payment:4001/
  #   routes:
  #   - name: payment
  #     paths:
  #       - /payment
  # - name: product
  #   url: grpc://product:50051
  #   routes:
  #   - name: product-routes
  #     protocols:
  #     - http
  #     paths:
  #     - /
  #     # strip_path: true
  #     headers: { 
  #       x-grpc :  [ 'true' ] 
  #     }
  #     plugins:
  #     - name: grpc-gateway
  #       config:
  #         proto: /opt/kong/product.proto

upstreams:
- name: product-http
  targets:
  - target: product:5000
    weight: 100
- name: booking-http
  targets:
  - target: booking:4000
    weight: 100